### ISSUE TITLE
no requirements.sh file

### ISSUE THREAD

**Issue by mmahdavian** [gftww/B2C#1]
Hello

Would you please provide the requirements.sh file to be able to install the package properly. The other package you have referred to doesn't provide it either. 

Thanks

**Comment by gftww** [comment]
Dear @mmahdavian:
Sorry for the late reply. Our code environment was mainly built based python>=3.8, torch, torchvision, and so on. You can refer to the requirement.txt.(pip install -r requirement.txt) Please check if the third-party package is complete.
[requirements.txt](https://github.com/gftww/B2C/files/13881887/requirements.txt)
Best Wishes

**Comment by mmahdavian** [comment]
Thank you for providing the file.
