### ISSUE TITLE
Pose2Feat issue

### ISSUE THREAD

**Issue by mmahdavian** [gftww/B2C#2]
Hello

I am trying to train the models with your codes. When I try to train the pose_only model, I get an error saying the input_dim size is 73, but the tensor sizes are 61 which comes from some lines in the Pose2Feat function. This is what I see:
```
        #self.input_dim = self.joint_num+3*self.skeleton_num
        #self.input_dim = self.joint_num
        #self.input_dim = self.skeleton_num
        #self.input_dim = self.joint_num+2*self.skeleton_num
        #self.input_dim = 3*self.skeleton_num
        
        self.input_dim = self.joint_num+4*self.skeleton_num
```
With the current uncommented line I get the error, but if I change it with the first line, the problem is solved. Would you please let me know what this line is doing? what are the 3 or 4 multiplied to the skeleton_num? and which one is the correct line to use? 

Thank You

**Comment by gftww** [comment]
Dear @mmahdavian 
Thanks for your code review. Those lines are set for ablation studies in the case of different combinations of pose features. You are right, and I forget to confirm it.
Please check the class **Model(nn.Module)** located in "~/B2C/main/model.py":
`
elif cfg.mode == 'pose_only':
            pose_feat = self.pose2feat(input_pose_hm, input_pose_limb_hm, input_pose_limb_mo)
            pose_feat = self.pose_backbone(pose_feat, skip_early=True)
            action_label_out = self.classifier(pose_feat)
            action_label_out = action_label_out.view(batch_size, pose_frame_num, -1).mean(1)
`
where the forward computation of self.pose2feat take "input_pose_hm, input_pose_limb_hm, input_pose_limb_mo" as input. 
**The "self.input_dim" is the sum of their dimensions.**
The "input_pose_hm" is the gaussian heatmaps of human joints, and its second dimension size = joint_num.  
The "input_pose_limb_hm" is the gaussian heatmaps of human limbs, and its second dimension size = skeleton_num. 
The "input_pose_limb_mo" is the motion vectors of human limbs, and it has two sub-directions (x- and y-), and its second dimension size = 2*skeleton_num.
Therefore, self.input_dim = joint_num + skeleton_num + 2*skeleton_num = joint_num +3*skeleton_num 
You can try it again.
Thanks a lot.
Best wishes.

**Comment by mmahdavian** [comment]
Thank You for your confirmation
