### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Sunshulong** [gftww/B2C#3]
Hello, can you take a look at the specific structure of your data set? Also, does the frames directory need to be divided into test sets and validation sets?

**Comment by gftww** [comment]
Sorry for the late reply:
Following the setting of [IntegralAction](https://github.com/mks0601/IntegralAction_RELEASE), there is no need to divide those frames into the test and validation sets.  The structure of the dataset is formed as:
> ${ROOT}  
|-- data  
|   |-- Kinetics
|   |   |-- data
|   |   |   |-- frames 
|   |   |   |-- kinetics-skeleton
|   |   |   |-- Kinetics50_train.json
|   |   |   |-- Kinetics50_val.json
|   |   |   |-- Kinetics400_train.json
|   |   |   |-- Kinetics400_val.json
|   |-- Mimetics
|   |   |-- data  
|   |   |   |-- frames 
|   |   |   |-- pose_results 
|   |   |   |-- Mimetics50.json
|   |   |   |-- Mimetics400.json
|   |-- NTU
|   |   |-- data  
|   |   |   |-- frames 
|   |   |   |-- nturgb+d_skeletons
|   |   |   |-- NTU_train.json
|   |   |   |-- NTU_test.json

**Comment by Sunshulong** [comment]
Thank you for your timely reply. I also want to ask the following questions. 
1. I would like to ask if I can reduce the data set? That is, only train some of the behaviors and delete other behaviors. 
2. In which file of the project should I modify the path of the data set? 
3. Could you please help me see if the structure of my data set is correct?
![image](https://github.com/gftww/B2C/assets/102716857/f570d01b-907c-4413-9019-759927ed9ce1)
![image](https://github.com/gftww/B2C/assets/102716857/a7967161-fcdc-4c14-95e1-b1ff48093206)

**Comment by gftww** [comment]
You are welcome.
Firstly, you can customize and modify the dataset according to your own needs;
Secondly, the python file located in "${ROOT}/data/${NTU/Kinetics/Mimetics}.py" involves the path of dataset;
For example, you can modify the line 18 in NTU.py:
` self.data_path = osp.join('/back/dataset/HumanAction/', 'data', 'NTU', 'data')` 
Finally, you data structure seems fine.

**Comment by Sunshulong** [comment]
哇  太谢谢了  您的意思是把数据集放到/back/dataset/HumanAction/data/NTU/data这个目录下吗？ 我在Window下运行的，这会有影响吗?

**Comment by Sunshulong** [comment]
Sorry to bother you, I reported this error 'ImportError: cannot import name 'model_urls' from 'torchvision.models.resnet' when I ran the project. I think it is a version problem of torchvision, so I would like to ask about your project. Version Information.

**Comment by gftww** [comment]
This error seems that the model_urls is no longer available for versions >0.13 in torchvision. Can you try torchvision==0.13.
