### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Sunshulong** [gftww/B2C#4]
![b15ccfbdcc4200be18b2b2a51354913e](https://github.com/gftww/B2C/assets/102716857/f1671212-76c6-44e2-ae72-bf74e91450a4)
The above are problems that arise during training.
Please help me find out where the problem is. Look at the code "ckpt=torch.load(ckpt_path)". Should there be an initial model file of pth.tar type in the project?

**Comment by gftww** [comment]
Each checkpoint model will be saved for each epoch during continued training. Can you check the code（located in line 31, `'B2C/main/train.py'）:
` cfg.set_args('0,1,2,3,4,5','rgb+pose', True)` 
to that
`cfg.set_args('0,1,2,3,4,5','rgb+pose', False)`
Sorry for this misleading default setting.

**Comment by Sunshulong** [comment]
Thank you for your reply, but I encountered the following problem. I would like to ask where should the configuration of the number of GPUs be modified in the project? The picture below is a problem I encountered. I came to ask you for advice because I really couldn't solve it. Hope to get your advice.
![8cdc1329b4f8c0a593d78e81c9e47ae2](https://github.com/gftww/B2C/assets/102716857/edf1228c-7de6-473a-a1a7-9428e9b24616)

**Comment by gftww** [comment]
Dear @Sunshulong ：
    May I have your attention on the train.py and config.py in the "main" file:
    The code `cfg.set_args('0,1,2,3,4,5','rgb+pose', False)` in line 35 of train.py will call the function `set_args()` in line 70 config.py.
In fact, when you set your GPU indexes (0,1,2,...)，and the numbers of GPU will be computed automatically.
For example, we you have two GPU named 0, and 1, and the code in line 35 of train.py can be replaced as below:
`cfg.set_args('0,1','rgb+pose', False)`.
of course, I just advise that you should start your training by rgb_only, pose_only and rgb+pose:
`cfg.set_args('0,1','rgb_only', False)`、`cfg.set_args('0,1','pose_only', False)`、`cfg.set_args('0,1','rgb+pose', False)`
That’s all.

**Comment by Sunshulong** [comment]
Thank you for your patient answer. The project is currently running successfully.
