### ISSUE TITLE
Test video

### ISSUE THREAD

**Issue by Sunshulong** [gftww/B2C#5]
Hello, I have taken the liberty to disturb you again. I have completed the project. Now I have a video. How can I monitor the behavior of the people in the video in real time?

**Comment by gftww** [comment]
Dear @Sunshulong 
We didn't provide the test file for unclipped video. If you want to monitor actions, you can follow the solutions in[ long video demos](https://github.com/open-mmlab/mmaction2/blob/main/demo/long_video_demo.py).

**Comment by Sunshulong** [comment]
Dear @gftww 
Thank you very much for your suggestions. Now I would like to ask where I should get the inference configuration file config.py of mmaction2. Should I configure it myself? I feel that writing the configuration file config.py is a bit difficult for me, so I would like to consult you below. 
Looking forward to your reply.

**Comment by gftww** [comment]
I apologize for not being able to further assist you on detials.
But you can follow these documents of [Kinetics-400](https://mmaction2.readthedocs.io/en/latest/model_zoo/recognition.html#kinetics-400), and there are config files that can be downloaded.
